Neos:
  EventSourcing:
    EventStore:
      stores:
        'Wwwision.EventScheduler':
          boundedContexts:
            'Wwwision.EventScheduler': true
          storage: 'Wwwision\EventScheduler\EventStore\TransientEventStorage'